---
title: "Examining the draft success of NFL teams using Pro Football Reference's Approximate Value statistic"
author: "Myron Keith Gibert Jr"
date: "March 4, 2020"
output: pdf_document
toc: true
---

## Introduction
For this first programming assignment I wrote three functions that are meant to interact with dataset that accompanies this assignment. The dataset is contained in a zip file specdata.zip that is included in the GitHub repository.

## Set parameters

```{r parameters}

outputdir <- "Outputs"

```

## Install required programs

```{r setup, message = FALSE}
knitr::opts_chunk$set(echo = TRUE)

if (!require("tidyverse")) install.packages("tidyverse")
library("tidyverse")

if (!require("ggplot2")) install.packages("ggplot2")
library("ggplot2")

if (!require("ggforce")) install.packages("ggforce")
library("ggforce")

if (!require("ggrepel")) install.packages("ggrepel")
library("ggrepel")

if (!require("ggfortify")) install.packages("ggfortify")
library("ggfortify")

```

```{r outputs}
if(!dir.exists(outputdir)){
  dir.create(outputdir)
}
```


```{r tinytex, include=FALSE}
## INSTALLING LATEX FOR RMARKDOWN

#RMarkdown requires LaTex to create pdf documents as an output. More information can be found [here](https://bookdown.org/yihui/rmarkdown/pdf-document.html). Alternatively, output can be set to "html_document" or "word_document". End users may install LaTex by setting the "wanttinytex" variable to FALSE and running the following script:

#Install tinytex to let RMarkdown create a pdf document? Default: wanttinytex <- FALSE
wanttinytex <- TRUE

if(tinytex:::is_tinytex()==FALSE && wanttinytex == TRUE){
if (!require("tinytex")) install.packages("tinytex")
tinytex::install_tinytex()
}
```

## Completing survival analysis for TUCRs

```{r getdata, message = FALSE}
if(!dir.exists("draftdata")){unzip("draftdata.zip")}

filenames <- list.files("./draftdata")

all_content <- readLines("draftvaluechart.csv")
skip_lines <- all_content[-1]
valuechart <- read.csv(textConnection(skip_lines), header = TRUE, stringsAsFactors = FALSE)
valuechart <- valuechart %>% select(Pick,"ExAV" = AV)
```

```{r master, message = FALSE}
i = 1

mastertable <- data.frame()

for(i in 1:length(filenames)){
  all_content = readLines(paste("./draftdata/",filenames[i],sep=""))
  draftyear <- substr(filenames[i], 1, 4)
  skip_lines = all_content[-1]
  x <- read.csv(textConnection(skip_lines), header = TRUE, stringsAsFactors = FALSE)
  x <- x %>% mutate(year = draftyear)
  mastertable <- rbind(mastertable,x)
}

mastertable <- mastertable %>% left_join(valuechart,by="Pick") 
mastertable[is.na(mastertable)] <- 0
mastertable <- mastertable %>% mutate(dif = DrAV - ExAV, hit = ifelse(dif>=0,1,0))
mastertable <- mastertable %>% group_by(Tm,year) %>% mutate(class.dif = sum(dif,na.rm=TRUE)) 

mastertable$Tm <- ifelse(mastertable$Tm == "STL","LAR",ifelse(mastertable$Tm == "SDG","LAC",mastertable$Tm))



teams <- unique(mastertable$Tm)
```

```{r summary}
summarytable <- mastertable %>%
  group_by(Tm) %>%
  summarise(hits = sum(hit,na.rm=TRUE),picks = length(hit),hit.percentage = hits/picks,totalvalue = sum(dif,na.rm=TRUE))
```

```{r bestvalueplayers}

bestvalueplayers <- mastertable %>% 
             group_by(Tm) %>%
             filter(dif == max(dif,na.rm=TRUE)) %>%
             select(year,Rnd,Pick,Tm,Player,Pos,ExAV,DrAV,dif)

```

```{r bestplayers}

bestplayers <- mastertable %>% 
             group_by(Tm) %>%
             filter(DrAV == max(DrAV,na.rm=TRUE)) %>%
             select(year,Rnd,Pick,Tm,Player,Pos,ExAV,DrAV,dif)

```

```{r biggestbusts}

biggestbusts <- mastertable %>% 
             group_by(Tm) %>%
             filter(year <= 2016) %>%
             filter(dif == min(dif,na.rm=TRUE)) %>%
             select(year,Rnd,Pick,Tm,Player,Pos,ExAV,DrAV,dif)

```

```{r eaglesplayers}

eaglesplayers <- mastertable %>% 
             filter(Tm == "PHI") %>%
             select(year,Rnd,Pick,Tm,Player,Pos,ExAV,DrAV,dif)

```
